controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: /api/v1

api_login_check:
    path: /api/v1/login_check

refresh_token:
    path: /api/v1/token/refresh
    controller: App\Controller\User\RefreshTokenController::refresh
    methods: [POST]