controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: /api/v1

api_login_check:
    path: /api/v1/login_check

api_auth_logout:
  path: /api/v1/auth/logout
  controller: App\Controller\User\AuthController::logout
  methods: [POST]